#                                                           Developed by Vasty
#                                                     (Aquatic Studios @ (C) 2016-2025)

name: AquaSpawn
version: '${version}'
authors: [Vasty]

main: dev.club.aquatic.AquaSpawn
api-version: '1.13'
website: https://github.com/aquaticstudios

commands:
  aquaspawn:
    description: Main command for AquaSpawn plugin